Trying multiple CPU arch builds

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,7 +16,7 @@ cache:
   paths:
     - ./.m2/repository
 
-test-job:
+test-job-amd64:
   stage: test 
   image: ridiekel/base-test:latest
   tags:
@@ -24,7 +24,8 @@ test-job:
   script:
     - |
       echo "Running native amd64 tests..."
-      ./mvnw $MAVEN_CLI_OPTS -PnativeTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
+      ./mvnw $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
+#      ./mvnw $MAVEN_CLI_OPTS -PnativeTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
       cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
   coverage: '/Total.*?([0-9]{1,3})%/'
   artifacts:
@@ -70,7 +71,7 @@ sonarqube-analysis:
     key: "${CI_JOB_NAME}"
     paths:
       - .sonar/cache
-  needs: ["test-job"]
+  needs: ["test-job-amd64"]
   script: 
     - mvn $MAVEN_CLI_OPTS sonar:sonar -Dmaven.test.failure.ignore=true
   allow_failure: true
@@ -85,7 +86,7 @@ code-coverage-report-conversion:
     - amd64
   script:
     - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
-  needs: ["test-job"]
+  needs: ["test-job-amd64"]
   artifacts:
     reports:
       coverage_report:
@@ -225,7 +226,7 @@ docker-build-and-push:
     - |
       set -euo pipefail
       TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
       VERSION="${TAG#${CI_PROJECT_NAME}-}"
       echo "TAG=$TAG VERSION=$VERSION"
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
@@ -236,46 +237,46 @@ docker-build-and-push:
       when: on_success
       allow_failure: false
 
-docker-build-and-push-native-arm64:
-  stage: release
-  tags:
-    - arm64
-  needs:
-    - job: create-release
-      artifacts: true
-    - job: test-job-arm64
-      artifacts: true
-  script:
-    - |
-      echo "TAG=$TAG VERSION=$VERSION"
-      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
-      MAVEN_OPTS=""
-      echo "Installing graalvm if not yet present"
-      sdk install java ${GRAALVM_VERSION}
-      sdk use java ${GRAALVM_VERSION}
-      echo "Installing maven if not yet present"
-      sdk install maven ${MAVEN_VERSION}
-      sdk use maven ${MAVEN_VERSION}
-      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
-      VERSION="${TAG#${CI_PROJECT_NAME}-}"
-      echo "Version is: ${VERSION}"
-      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-arm64"
-      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-arm64"
-      echo "Versioned image name is: ${IMAGE_VERSIONED}"
-      echo "Latest image name is: ${IMAGE_LATEST}"
-      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-      echo "Running native arm64 build..."
-      ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
+#docker-build-and-push-native-arm64:
+#  stage: release
+#  tags:
+#    - arm64
+#  needs:
+#    - job: create-release
+#      artifacts: true
+#    - job: test-job-arm64
+#      artifacts: true
+#  script:
+#    - |
+#      echo "TAG=$TAG VERSION=$VERSION"
+#      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
+#      MAVEN_OPTS=""
+#      echo "Installing graalvm if not yet present"
+#      sdk install java ${GRAALVM_VERSION}
+#      sdk use java ${GRAALVM_VERSION}
+#      echo "Installing maven if not yet present"
+#      sdk install maven ${MAVEN_VERSION}
+#      sdk use maven ${MAVEN_VERSION}
+#      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
+#      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+#      VERSION="${TAG#${CI_PROJECT_NAME}-}"
+#      echo "Version is: ${VERSION}"
+#      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-arm64"
+#      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-arm64"
+#      echo "Versioned image name is: ${IMAGE_VERSIONED}"
+#      echo "Latest image name is: ${IMAGE_LATEST}"
+#      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+#      echo "Running native arm64 build..."
+#      ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
 #      echo "Tag latest"
-      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
-      #echo "Push both tags"
-      #docker push "${IMAGE_VERSIONED}"
-      #docker push "${IMAGE_LATEST}"
-  rules:
-    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
-      when: on_success
-      allow_failure: false
+#      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+#      echo "Push both tags"
+#      docker push "${IMAGE_VERSIONED}"
+#      docker push "${IMAGE_LATEST}"
+#  rules:
+#    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
+#      when: on_success
+#      allow_failure: false
 
 docker-build-and-push-native-amd64-v1:
   stage: release
@@ -294,7 +295,7 @@ docker-build-and-push-native-amd64-v1:
 
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
       TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
 
       VERSION="${TAG#${CI_PROJECT_NAME}-}"      
       echo "Version is: ${VERSION}"
@@ -330,6 +331,7 @@ docker-build-and-push-native-amd64-v2:
       artifacts: true
   script:
     - |
+      set -x
       VERSION_SUFFIX="-v2"      
       export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-v2"
       export BP_LOG_LEVEL=DEBUG
@@ -338,7 +340,7 @@ docker-build-and-push-native-amd64-v2:
 
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
       TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
 
       VERSION="${TAG#${CI_PROJECT_NAME}-}"      
       echo "Version is: ${VERSION}"
@@ -387,7 +389,7 @@ docker-build-and-push-native-amd64-v3:
 
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
       TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
 
       VERSION="${TAG#${CI_PROJECT_NAME}-}"      
       echo "Version is: ${VERSION}"
@@ -430,7 +432,7 @@ docker-build-and-push-native-amd64-v4:
 
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
       TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-      test -n "$TAG" || { echo "Geen tag gevonden (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
 
       VERSION="${TAG#${CI_PROJECT_NAME}-}"      
       echo "Version is: ${VERSION}"
