Trying multiple CPU arch builds

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -24,8 +24,7 @@ test-job-amd64:
   script:
     - |
       echo "Running native amd64 tests..."
-      ./mvnw $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
-      #./mvnw $MAVEN_CLI_OPTS -PnativeTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
+      ./mvnw $MAVEN_CLI_OPTS -PnativeTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
       cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
   coverage: '/Total.*?([0-9]{1,3})%/'
   artifacts:
@@ -54,7 +53,7 @@ test-job-arm64:
       sdk install maven ${MAVEN_VERSION}
       sdk use maven ${MAVEN_VERSION}
       echo "Running native arm64 tests..."
-      #./mvnw $MAVEN_CLI_OPTS -PnativeTest verify
+      ./mvnw $MAVEN_CLI_OPTS -PnativeTest verify
   rules:
     - if: $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
       when: always
@@ -124,7 +123,7 @@ create-release:
   artifacts:
     paths:
       - target/jeletask*.jar
-      - release.properties       # optioneel, handig voor debug
+      - release.properties
       - variables.env
       - Dockerfile
     reports:
@@ -231,54 +230,54 @@ docker-build-and-push:
       echo "TAG=$TAG VERSION=$VERSION"
       IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
       echo "IMAGE=$IMAGE"
-      #docker buildx build --platform linux/amd64,linux/arm64 -t "$IMAGE:latest" -t "$IMAGE:$VERSION" --push .
+      docker buildx build --platform linux/amd64,linux/arm64 -t "$IMAGE:latest" -t "$IMAGE:$VERSION" --push .
   rules:
     - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
       when: on_success
       allow_failure: false
 
-#docker-build-and-push-native-arm64:
-#  stage: release
-#  tags:
-#    - arm64
-#  needs:
-#    - job: create-release
-#      artifacts: true
-#    - job: test-job-arm64
-#      artifacts: true
-#  script:
-#    - |
-#      echo "TAG=$TAG VERSION=$VERSION"
-#      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
-#      MAVEN_OPTS=""
-#      echo "Installing graalvm if not yet present"
-#      sdk install java ${GRAALVM_VERSION}
-#      sdk use java ${GRAALVM_VERSION}
-#      echo "Installing maven if not yet present"
-#      sdk install maven ${MAVEN_VERSION}
-#      sdk use maven ${MAVEN_VERSION}
-#      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
-#      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
-#      VERSION="${TAG#${CI_PROJECT_NAME}-}"
-#      echo "Version is: ${VERSION}"
-#      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-arm64"
-#      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-arm64"
-#      echo "Versioned image name is: ${IMAGE_VERSIONED}"
-#      echo "Latest image name is: ${IMAGE_LATEST}"
-#      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-#      echo "Running native arm64 build..."
-#      ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
-#      echo "Tag latest"
-#      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
-#      echo "Push both tags"
-#      docker push "${IMAGE_VERSIONED}"
-#      docker push "${IMAGE_LATEST}"
-#  rules:
-#    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
-#      when: on_success
-#      allow_failure: false
+docker-build-and-push-native-arm64:
+  stage: release
+  tags:
+    - arm64
+  needs:
+    - job: create-release
+      artifacts: true
+    - job: test-job-arm64
+      artifacts: true
+  script:
+    - |
+      echo "TAG=$TAG VERSION=$VERSION"
+      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
+      MAVEN_OPTS=""
+      echo "Installing graalvm if not yet present"
+      sdk install java ${GRAALVM_VERSION}
+      sdk use java ${GRAALVM_VERSION}
+      echo "Installing maven if not yet present"
+      sdk install maven ${MAVEN_VERSION}
+      sdk use maven ${MAVEN_VERSION}
+      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+      VERSION="${TAG#${CI_PROJECT_NAME}-}"
+      echo "Version is: ${VERSION}"
+      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-arm64"
+      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-arm64"
+      echo "Versioned image name is: ${IMAGE_VERSIONED}"
+      echo "Latest image name is: ${IMAGE_LATEST}"
+      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+      echo "Running native arm64 build..."
+      ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}"
+      echo "Tag latest"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+      echo "Push both tags"
+      docker push "${IMAGE_VERSIONED}"
+      docker push "${IMAGE_LATEST}"
+  rules:
+    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
+      when: on_success
+      allow_failure: false
 
-docker-build-and-push-native-amd64-v2:
+docker-build-and-push-native-amd64-v1:
   stage: release
   image: ridiekel/base-test:latest
   tags:
@@ -289,8 +288,8 @@ docker-build-and-push-native-amd64-v2:
   script:
     - |
       set -x
-      VERSION_SUFFIX="-v2"      
-      export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-v2"
+      VERSION_SUFFIX="-v1"      
+      export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-${VERSION_SUFFIX}"
 
       echo "TAG=$TAG VERSION=$VERSION"
 
@@ -315,12 +314,158 @@ docker-build-and-push-native-amd64-v2:
         spring-boot:build-image \
         -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}" \
         -Dspring-boot.build-image.environment.BP_NATIVE_IMAGE_BUILD_ARGUMENTS="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
-      #echo "Tag latest"
-      #docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
-      #echo "Push both tags"
-      #docker push "${IMAGE_VERSIONED}"
-      #docker push "${IMAGE_LATEST}"
+      echo "Tag latest"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+      echo "Push both tags"
+      docker push "${IMAGE_VERSIONED}"
+      docker push "${IMAGE_LATEST}"
   rules:
     - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
       when: on_success
       allow_failure: false
+
+docker-build-and-push-native-amd64-v2:
+  stage: release
+  image: ridiekel/base-test:latest
+  tags:
+    - amd64
+  needs:
+    - job: create-release
+      artifacts: true
+  script:
+    - |
+      set -x
+      VERSION_SUFFIX="-v2"      
+      export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-${VERSION_SUFFIX}"
+
+      echo "TAG=$TAG VERSION=$VERSION"
+
+      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
+      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+
+      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
+      echo "Version is: ${VERSION}"
+      
+      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
+      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
+      echo "Versioned image name is: ${IMAGE_VERSIONED}"
+      echo "Latest image name is: ${IMAGE_LATEST}"
+      
+      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+      
+      echo "Running native amd64 build..."
+      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" \
+        -DskipTests \
+        spring-boot:build-image \
+        -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}" \
+        -Dspring-boot.build-image.environment.BP_NATIVE_IMAGE_BUILD_ARGUMENTS="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      echo "Tag latest"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+      echo "Push both tags"
+      docker push "${IMAGE_VERSIONED}"
+      docker push "${IMAGE_LATEST}"
+  rules:
+    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
+      when: on_success
+      allow_failure: false
+
+docker-build-and-push-native-amd64-v3:
+  stage: release
+  image: ridiekel/base-test:latest
+  tags:
+    - amd64
+  needs:
+    - job: create-release
+      artifacts: true
+  script:
+    - |
+      set -x
+      VERSION_SUFFIX="-v3"      
+      export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-${VERSION_SUFFIX}"
+
+      echo "TAG=$TAG VERSION=$VERSION"
+
+      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
+      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+
+      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
+      echo "Version is: ${VERSION}"
+      
+      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
+      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
+      echo "Versioned image name is: ${IMAGE_VERSIONED}"
+      echo "Latest image name is: ${IMAGE_LATEST}"
+      
+      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+      
+      echo "Running native amd64 build..."
+      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" \
+        -DskipTests \
+        spring-boot:build-image \
+        -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}" \
+        -Dspring-boot.build-image.environment.BP_NATIVE_IMAGE_BUILD_ARGUMENTS="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      echo "Tag latest"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+      echo "Push both tags"
+      docker push "${IMAGE_VERSIONED}"
+      docker push "${IMAGE_LATEST}"
+  rules:
+    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
+      when: on_success
+      allow_failure: false
+
+docker-build-and-push-native-amd64-v4:
+  stage: release
+  image: ridiekel/base-test:latest
+  tags:
+    - amd64
+  needs:
+    - job: create-release
+      artifacts: true
+  script:
+    - |
+      set -x
+      VERSION_SUFFIX="-v4"      
+      export BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-march=x86-64-${VERSION_SUFFIX}"
+
+      echo "TAG=$TAG VERSION=$VERSION"
+
+      IMAGE="${DOCKERHUB_IMAGE:-${DOCKERHUB_USERNAME}/${CI_PROJECT_NAME}}"
+      TAG="${scm_tag:-${CI_COMMIT_TAG:-}}"
+      test -n "$TAG" || { echo "Could not find tag (scm_tag/CI_COMMIT_TAG)"; exit 1; }
+
+      VERSION="${TAG#${CI_PROJECT_NAME}-}"      
+      echo "Version is: ${VERSION}"
+      
+      IMAGE_VERSIONED="${DOCKERHUB_IMAGE}:${VERSION}-native-amd64${VERSION_SUFFIX}"
+      IMAGE_LATEST="${DOCKERHUB_IMAGE}:latest-native-amd64${VERSION_SUFFIX}"
+      echo "Versioned image name is: ${IMAGE_VERSIONED}"
+      echo "Latest image name is: ${IMAGE_LATEST}"
+      
+      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+      
+      echo "Running native amd64 build..."
+      echo "Architecture: ${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      ./mvnw $MAVEN_CLI_OPTS -Pnative -Dnative-image.args="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}" \
+        -DskipTests \
+        spring-boot:build-image \
+        -Dspring-boot.build-image.imageName="${IMAGE_VERSIONED}" \
+        -Dspring-boot.build-image.environment.BP_NATIVE_IMAGE_BUILD_ARGUMENTS="${BP_NATIVE_IMAGE_BUILD_ARGUMENTS}"
+      echo "Tag latest"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST}"
+      echo "Push both tags"
+      docker push "${IMAGE_VERSIONED}"
+      docker push "${IMAGE_LATEST}"
+
+      IMAGE_LATEST_NATIVE="${DOCKERHUB_IMAGE}:latest-native-amd64"
+      docker tag "${IMAGE_VERSIONED}" "${IMAGE_LATEST_NATIVE}"
+      docker push "${IMAGE_LATEST_NATIVE}"
+  rules:
+    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TITLE !~ /^\[maven-release-plugin\].*/
+      when: on_success
+      allow_failure: false
+
